import Head from "next/head";

import styles from "./index.module.css";
import { env } from "~/env";
import { Button, ButtonGroup, Container, Heading } from "@chakra-ui/react";
import { useRouter } from "next/router";
import axios from "axios";

export default function Home() {
  const router = useRouter();
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Container marginTop={8}>
          <Heading> Mis Ventas</Heading>
          <ButtonGroup>
            <Button colorScheme='blue' onClick={() => router.push("/login")}>Login</Button>
            <Button colorScheme='green' onClick={() => {
              axios.get(`${env.NEXT_PUBLIC_BACKEND_BASE_URL}/sales`, {withCredentials: true})
            }}>Sales</Button>
            <Button colorScheme='purple' onClick={() => {
              axios.post(`${env.NEXT_PUBLIC_BACKEND_BASE_URL}/sales`, 
                {
                  operation_date: new Date(),
                  total_amount: 2800,
                },
                {withCredentials: true})
            }}>Created Sale</Button>
          </ButtonGroup>
          
      </Container>
    </>
  );
}
