import Head from "next/head";

import styles from "./index.module.css";
import { env } from "~/env";
import { Button, ButtonGroup, Card, Container, Heading } from "@chakra-ui/react";
import { useRouter } from "next/router";
import axios from "axios";

export default function Home() {
  const router = useRouter();
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Container marginTop={8}>
        <Card padding={4}>
          <Heading> Mis Ventas</Heading>
            <ButtonGroup mt={8}>
              <Button colorScheme='blue' onClick={() => router.push("/login")}>Login</Button>
              <Button colorScheme='purple' onClick={() => {
                router.push("/clients")
              }}>Clientes</Button>
            </ButtonGroup>
        </Card>
          
      </Container>
    </>
  );
}
